<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class UrlTest extends TestCase
{
    use DatabaseMigrations;
    use DatabaseTransactions;

    private int $id;
    private array $domain;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->domain = ['name' => 'https://google.com'];
        $this->id = DB::table('urls')->insertGetId($this->domain);
    }

    public function testUrlStore()
    {
        $response = $this
            ->post(route('urls.store'), ['url' => $this->domain])
            ->assertRedirect(route('urls.show', ['url' => $this->id]));
        $response->assertSessionHasNoErrors();
        $this->assertDatabaseCount('urls', 1);
        $this->assertDatabaseHas('urls', ['name' => 'https://google.com']);
    }

    public function testUrlIndex()
    {
        $response = $this->get(route('urls.index'));
        $response->assertOk();
    }

    public function testUrlShow()
    {
        $response = $this->get(route('urls.show', ['url' => $this->id]));
        $response->assertOk();
    }
}
